### ISSUE TITLE
Insert Special Cartridges 

### ISSUE THREAD

**Issue by andrea9292** [CocoaMSX/CocoaMSX#24]
In BlueMSX 2.8.2, we can insert special cartridges via menu such is FM-PAC etc. Please implement this facility in CocoaMSX.

**Comment by andrea9292** [comment]
Hello? Can I inseert special cartridge in CocoaMSX now?

**Comment by 0xe1f** [comment]
You can, actually. For example, this is how you'd go about inserting an SCC+ cartridge: https://github.com/CocoaMSX/CocoaMSX/wiki/Enabling-Konami-Sound-Cartridge-%28SCC-Plus%29-support

**Comment by 0xe1f** [comment]
Closing, since special cartridges can be inserted by selecting appropriate ROM + ROM type.
