### ISSUE TITLE
MacBook Pro internal keyboard not working

### ISSUE THREAD

**Issue by dixius99** [CocoaMSX/CocoaMSX#45]
I can use the emulator fine using default settings so long as I use an external keyboard. When I use the built-in internal keyboard on my 2010 13" MBP, the keyboard doesn't appear to work at all, and trying to remap buttons in preferences does nothing either. Not sure if there is a setting I'm overlooking to resolve this?

EDIT: Just to add, it doesn't seem to matter whether an external keyboard is connected or not. The internal keyboard simply doesn't want to work for me, even when it is the only keyboard.

**Comment by pokebyte** [comment]
I have a 2012 13" MBP, and I don't have any issues with the keyboard. What OS are you running?

**Comment by dixius99** [comment]
I'm running 10.12.6.

**Comment by pokebyte** [comment]
Can you try an older release - e.g. https://github.com/CocoaMSX/CocoaMSX/releases/tag/v1.42 and let me know if you run into the same problem?

**Comment by dixius99** [comment]
Same thing, BUT, I think I discovered the cause. I also run [Karabiner Elements](https://github.com/tekezo/Karabiner-Elements) to customize my keys, but only for the internal keyboard. When I disable Karabiner Elements, I can then remap controls, etc. using the internal keyboard.

**Comment by pokebyte** [comment]
Thanks for the update.
